### ISSUE TITLE
R2Up and R3 moves not correct

### ISSUE THREAD

**Issue by mattrathbun** [mattrathbun/Evolutionary-Algorithms-for-Knot-Theory#9]
There are 4 recurring issues that crop up on repeated runs of TestSystem.py, which are likely inter-related.

1) There are mistakes in the results of R2Up moves. The results are sometimes not realizable diagrams (verified both by the isrealisable() method, and by hand). I am not sure why at this moment. Examples have been included into the TestR2Up.py file. Sample traceback included below:

>Traceback (most recent call last):
  File "TestSystem.py", line 25, in <module>
    inv = TestInverses.findInverse(M, i)
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/Testing/TestInverses.py", line 25, in findInverse
    move.apply(Ktemp)
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/ADTOp.py", line 166, in apply
    raise TypeError("We have a problem!!!")
>TypeError: We have a problem!!!

2) There are mistakes in the results of R3 moves. Sometimes the diagrams are not realizable. Examples have been included into the TestR3.py file. It looks as though the problem is just one of signs, though sign errors seem to be happening in both the code and the orientations. Sample traceback included below: 

>Traceback (most recent call last):
  File "TestSystem.py", line 25, in <module>
    inv = TestInverses.findInverse(M, i)
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/Testing/TestInverses.py", line 25, in findInverse
    move.apply(Ktemp)
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/ADTOp.py", line 166, in apply
    raise TypeError("We have a problem!!!")
>TypeError: We have a problem!!!

3) There is a bit in findInverse that should never be called, because all moves should have inverses (except for a couple of trivial 0- and 1-crossing diagram cases, which are now being treated separately). This almost certainly has to do with the two errors above, and 'moves' being performed on non-realizable diagrams which then do not admit inverses since they are not properly allowed to begin with. Traceback included below:

>Traceback (most recent call last):
  File "TestSystem.py", line 50, in <module>
    print i.toString()
>AttributeError: 'list' object has no attribute 'toString'

(Note that findInverse is returning a list as part of de-bugging, because this section of code should never have to run.)

4) There is a very strange IndexError that arises sometimes. Further investigation shows that it occurs when the 'code' of an ADT object does not make sense, e.g. has odd numbers, repetitions, zeros, or negative numbers. Again, this is almost certainly related to 1 and 2 above. Traceback included below:

>Traceback (most recent call last):
  File "TestSystem.py", line 22, in <module>
    if i.apply(L):
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/ADTOp.py", line 159, in apply
    if knot.isrealisable():
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/ADT.py", line 896, in isrealisable
    a_s = self.jump(s)
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/ADT.py", line 148, in jump
    odd, even, sign, orient = self.quad(point)
  File "/Users/Matt/Documents/Python/Knotting/Github/Evolutionary-Algorithms-for-Knot-Theory/Python/ADT.py", line 138, in quad
    idx = [i for i, j in enumerate(code) if abs(j) == even][0]
>IndexError: list index out of range

**Comment by mattrathbun** [comment]
These issues all seem to have been resolved. If new (systematic) testing gives rise to errors, we will open a new ticket.
